// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

export const environment = {
  production: false,
  // Update this token to match the token generated by the api after setting unique secret and key environmental variables.
  api_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOiJwb3RhdG9mYW1pbmUifQ.J4F1izRgTlVLjPloan3NEnU4xVpSEIl4uQZNau08KPo",
};
